### ISSUE TITLE
NonSPH Has a couple errors

### ISSUE THREAD

**Issue by watameln** [Dragoon-s-Den/DragoonTankSystem#1]
![image](https://github.com/user-attachments/assets/87caff2d-d866-4ca7-8471-967438f7aea7)

Fixable but would be confusing for people who don't know how it works.

**Comment by Jarrrrrr06** [comment]
Resolved in 1.0.1
ExplosionFX is no longer required by DTS, and the other SPH modules are now included into the single version package.
Now it detects existing Spearhead installation and defaults to its own modules if none is found.
